apiVersion: v2
name: cheeta
version: ${buildVersion}
description: All-In-One DevOps Platform
type: application
keywords:
  - cheeta
  - devops
  - vcs
  - cicd
home: https://cheeta.io
maintainers:
  - name: Robin Shen
    email:  robin@cheeta.io
  - name: Abdul Khaliq
    email: a.khaliq@outlook.my
appVersion: ${buildVersion}
